<a href="https://colab.research.google.com/github/apurvak3/Machine_Learning/blob/main/Ensemble_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Function to convert boolean columns to integers (0 or 1)
def convert_bool_to_int_columns(df):
    """
    Converts all boolean columns in a DataFrame to integer type (0 for False, 1 for True).
    """
    for col in df.select_dtypes(include='bool').columns:
        df[col] = df[col].astype(int)
    return df

In [21]:
df = pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

In [22]:
df.head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [24]:
df.TotalCharges= pd.to_numeric(df.TotalCharges, errors='coerce')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [26]:
df.dropna(how='any', inplace=True)

In [27]:
len(df)

7032

In [28]:
df.Churn.value_counts()/len(df)*100

Churn
No     73.421502
Yes    26.578498
Name: count, dtype: float64

In [29]:
X= df.drop(['customerID', 'Churn'], axis=1)

In [30]:
y=df.Churn.values

In [31]:
#convert categorical features to numerical  -> feature encoding -> dummy encoding
X = pd.get_dummies(X, columns=['gender', 'Partner', 'Dependents','PhoneService','MultipleLines', 'InternetService','OnlineSecurity','OnlineBackup',
'DeviceProtection', 'TechSupport','StreamingTV','StreamingMovies', 'Contract', 'PaperlessBilling','PaymentMethod'], drop_first=True)

In [38]:
X = convert_bool_to_int_columns(X)
X.head()

   SeniorCitizen  ...  PaymentMethod_Mailed check
0              0  ...                           0
1              0  ...                           1
2              0  ...                           1
3              0  ...                           0
4              0  ...                           0

[5 rows x 30 columns]

In [17]:
X.head()

   SeniorCitizen  ...  PaymentMethod_Mailed check
0              0  ...                       False
1              0  ...                        True
2              0  ...                        True
3              0  ...                       False
4              0  ...                       False

[5 rows x 30 columns]

In [34]:

from sklearn.model_selection import train_test_split
X_train, X_test , y_train , y_test = train_test_split(X,y , test_size=0.25)

In [35]:
len(X_train)

5274

In [36]:
len(X_train)

5274

In [42]:
from sklearn.ensemble import RandomForestClassifier
model_rf= RandomForestClassifier(n_estimators=200)
model_rf.fit(X_train, y_train)
y_pred_rf=model_rf.predict(X_test)
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

          No       0.82      0.90      0.86      1277
         Yes       0.65      0.47      0.55       481

    accuracy                           0.79      1758
   macro avg       0.74      0.69      0.70      1758
weighted avg       0.77      0.79      0.78      1758

In [41]:
from sklearn.naive_bayes import BernoulliNB
model_nb= BernoulliNB()
model_nb.fit(X_train, y_train)
y_pred_nb= model_nb.predict(X_test)
print(classification_report(y_test, y_pred_nb))

              precision    recall  f1-score   support

          No       0.89      0.67      0.77      1277
         Yes       0.47      0.78      0.59       481

    accuracy                           0.70      1758
   macro avg       0.68      0.72      0.68      1758
weighted avg       0.77      0.70      0.72      1758

In [39]:
##Ensemble learning Adaboost Classifier
from sklearn.ensemble import  AdaBoostClassifier
from sklearn.metrics import classification_report
model_ada= AdaBoostClassifier(n_estimators=200)
model_ada.fit(X_train, y_train)
y_pred_ada=model_ada.predict(X_test)
print(classification_report(y_test, y_pred_ada))

              precision    recall  f1-score   support

          No       0.83      0.90      0.86      1277
         Yes       0.66      0.50      0.57       481

    accuracy                           0.79      1758
   macro avg       0.74      0.70      0.72      1758
weighted avg       0.78      0.79      0.78      1758

In [46]:
#gradient boost
from sklearn.ensemble import GradientBoostingClassifier
model_gb=GradientBoostingClassifier(n_estimators=200)
model_gb.fit(X_train , y_train)
y_pred_gb = model_gb.predict(X_test)
print(classification_report(y_test, y_pred_gb))

              precision    recall  f1-score   support

          No       0.83      0.89      0.86      1277
         Yes       0.65      0.52      0.58       481

    accuracy                           0.79      1758
   macro avg       0.74      0.71      0.72      1758
weighted avg       0.78      0.79      0.78      1758

In [48]:
from sklearn.metrics import accuracy_score
print("Accuracy of gb :" , accuracy_score(y_test , y_pred_gb))

Accuracy of gb : 0.7923777019340159

In [50]:
y[y=='No']=0
y[y=='Yes']=1
y=y.astype(int)

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test , y_train , y_test = train_test_split(X , y , test_size=0.25)
#feature scaling
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train_sc= sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [57]:
#xgboost
from xgboost import XGBClassifier
model_xgb= XGBClassifier(n_estimators=200)
model_xgb.fit(X_train_sc, y_train)
y_pred_xgb= model_xgb.predict(X_test_sc)
print(classification_report(y_test, y_pred_xgb))

              precision    recall  f1-score   support

           0       0.83      0.88      0.85      1280
           1       0.61      0.52      0.56       478

    accuracy                           0.78      1758
   macro avg       0.72      0.70      0.71      1758
weighted avg       0.77      0.78      0.77      1758

In [ ]:
xg boost mei we need to make y variable numerical.